name: Release package

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 # https://github.com/actions/checkout

      - name: Check if source code changed
        id: changed-files
        uses: tj-actions/changed-files@v40 # https://github.com/marketplace/actions/changed-files
        with:
          files_ignore: |
            .editorconfig
            .eslintrc.json
            .github/**
            .gitignore
            .npmignore
            vitest.config.js

      - uses: actions/setup-node@v3
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          node-version: "20"
          registry-url: https://registry.npmjs.org/

      - name: Get package version and check it has not been published
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          RELEASE_TAG=$(npm pkg get version | tr -d \")
          echo "RELEASE_TAG=$RELEASE_TAG" >> $GITHUB_ENV

      - name: Generate GitHub tag and release
        if: steps.changed-files.outputs.any_changed == 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_TAG: ${{ env.RELEASE_TAG }}
        run: |
          gh release create "$RELEASE_TAG" \
            --repo="$GITHUB_REPOSITORY" \
            --title="${GITHUB_REPOSITORY#*/} ${RELEASE_TAG}" \
            --generate-notes

      - name: Publish to NPMJS
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          npm install
          npm run build
          npm publish --verbose --tag latest
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPMJS_TOKEN }}
