name: Tests

on: pull_request

jobs:
  test:
    name: Run tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    permissions:
      # Required to check out the code
      contents: read
      # Required to put a comment into the pull-request
      pull-requests: write

    steps:
      - uses: actions/checkout@v4 # https://github.com/actions/checkout

      - uses: actions/setup-node@v4 # https://github.com/actions/setup-node
        with:
          node-version: "20"

      - name: Check if source code changed
        id: changed-files
        uses: tj-actions/changed-files@v42 # https://github.com/marketplace/actions/changed-files
        with:
          files_ignore: |
            .editorconfig
            .eslintrc.json
            .github/**
            .gitignore
            .npmignore
            vitest.config.js

      - uses: kriasoft/check-version@v1 # https://github.com/kriasoft/check-version
        if: steps.changed-files.outputs.any_changed == 'true'

      - name: Install dependencies
        run: npm install

      - name: Run tests and code coverage
        run: npm run coverage

      - name: 'Report Coverage'
        if: always()
        uses: davelosert/vitest-coverage-report-action@v2 # https://github.com/marketplace/actions/vitest-coverage-report
        with:
          file-coverage-mode: all
